---
  # Addon config file.
  # List out containers and the dockerfile that updates that continer.
espstreamview:
  dockerfile: Dockerfile_espstreamviewer
espstudio:
  dockerfile: Dockerfile_espstudio
httpproxy:
  dockerfile: Dockerfile_http
vipresm:
  dockerfile: Dockerfile_vipresm