---
# tasks file for tini

- name: Get epoch and use that as our id
  local_action: set_fact tmpcertloc="{{ '/tmp/tmp.' + ansible_date_time.epoch }}"
  run_once: yes

- name: Create temporary directory on remote machine
  file:
    path: "{{ tmpcertloc }}"
    state: directory

- name: Set the location of the temp directory
  set_fact:
    METAREPO_CERT_DIR: "{{ tmpcertloc }}"

- block:

  - name: Rebuild rpm db
    shell: rpm --rebuilddb

  - name: Install tini
    shell: |
      curl --insecure --output {{ METAREPO_CERT_DIR }}/{{ tini_rpm_name }} --location {{ tini_rpm_url }}
      yum install --assumeyes {{ METAREPO_CERT_DIR }}/{{ tini_rpm_name }}

  - name: Clean up yum
    shell: |
      yum clean all
      rm --recursive --force /root/.cache /var/cache/yum

  when:
  - ansible_os_family == 'RedHat'

- name: Remove temporary directory {{ METAREPO_CERT_DIR }}
  file:
    path: "{{ METAREPO_CERT_DIR }}"
    state: absent
