# This playbook is added to every Docker container used to install each Ansible role
--- 
- name: Install a role that's included in the config.yml
  hosts: 127.0.0.1
  connection: local
  roles:
  - "{{ layer }}"
  vars_files:
  - vars.yml
  - all.yml
  - soe_defaults.yml
  - extravars.yml
