---
- name: Create temporary directory on remote machine
  file:
    path: "{{ playbook_dir + '/manifests/' + item }}"
    state: directory
  with_items:
  - "kubernetes"
  - "kubernetes/deployments"
  - "kubernetes/configmap"
  - "kubernetes/secrets"
  - "compose"

- block:
    - name: Create k8s configmaps
      template:
        src: "k8s_configmap.j2"
        dest: "{{ playbook_dir }}/manifests/kubernetes/configmap/{{ item.key }}.yml"
      when: item.value.deployment_overrides.environment is defined and item.value.deployment_overrides.environment
      with_dict: '{{ services }}'

    - name: Create k8s secrets
      template:
        src: "k8s_secrets.j2"
        dest: "{{ playbook_dir }}/manifests/kubernetes/secrets/{{ item.key }}.yml"
      when: item.value.deployment_overrides.secrets is defined and item.value.deployment_overrides.secrets
      with_dict: '{{ services }}'

    - name: Create pets k8s manifest
      template:
        src: "pets_k8s.j2"
        dest: "{{ playbook_dir }}/manifests/kubernetes/deployments/{{ item.key }}.yml"
      when: item.key in 'httpproxy, pgpoolc, programming, rabbitmq, sas-casserver-primary, sasdatasvrc'
      with_dict: '{{ services }}'

    - name: Create CAS worker manifest
      template:
        src: "casworker_k8s.j2"
        dest: "{{ playbook_dir }}/manifests/kubernetes/deployments/sas-casserver-worker.yml"
      when: item.key in 'sas-casserver-primary'
      with_dict: '{{ services }}'

  when: manifest_type == 'kubernetes' or manifest_type == 'all'

- block:

    - name: Create docker-compose file
      template:
        src: "compose.j2"
        dest: "{{ playbook_dir }}/manifests/compose/docker-compose.yml"

  when: manifest_type == 'compose' or manifest_type == 'all'
