---
# Addon config file.
# List out containers and the dockerfile that updates the container that is being built.
httpproxy:
  dockerfile: Dockerfile_http
computeserver:
  dockerfile: Dockerfile
programming:
  dockerfile: Dockerfile