---
# tasks file for sas-install

- block:

  - name: Rebuild rpm db
    shell: rpm --rebuilddb

  - name: Install required packages
    yum:
      name: "{{ item }}"
      state: "present"
    with_items:
    - initscripts
    - which
    - acl
    - libpng12
    - libXp
    - libXmu
    - net-tools
    - xterm
    - numactl # ESM

  - name: Clean up yum cache
    shell: |
      yum clean all
      rm --recursive --force /root/.cache /var/cache/yum

  when:
  - ansible_os_family == 'RedHat'

- block:

  - name: Install required packages
    zypper:
      name: "{{ item }}"
      state: "present"
      disable_gpg_check: yes
    with_items:
    - initscripts
    - which
    - acl
    - libpng12
    - libXp
    - libXmu
    - net-tools
    - xterm
    - numactl # ESM

  when:
  - ansible_os_family == 'Suse'

- name: Remove nproc file
  file:
    path: /etc/security/limits.d/20-nproc.conf
    state: absent
